name: Ruby

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby 3.1
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.1.x
      - name: Build and test with Rake
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec middleman build --verbose
      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
      - name: Setup netlify
        run: |
          npm install -g netlify-cli
      - name: Deploy to netlify
        run: |
          netlify deploy --prod --message "Deploying from master" --auth ${{ secrets.NETLIFY_TOKEN }}
